---
version: '3'
services:
    build:
        context: ./docker
    volumes:
        - './app:/var/www/html'
    
    tomcat:
        image: tomcat:8-alpine
        ports:
            - '80:80'
        volumes:
            - './app:/var/www/html'     

...